import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "../ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <Sidebar />
      <div>
        <h1 className="font-bold text-2xl py-2 px-4">Dasboard</h1>
        {children}
      </div>
    </div>
  );
}
